---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alcide-advisor
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  # Keep the last run 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1  
  # Concurrency is not required
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: alcide-advisor
          initContainers:
          - name: fresh-ca-certs
            image: {{ .Values.images.initContainerImage }}
            command:
            - sh
            - -c
            - cp /etc/ssl/certs/* /certs/
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              runAsUser: 10001
              readOnlyRootFilesystem: true
            volumeMounts:
            - name: ca-certificates
              mountPath: /certs
          containers:
          - name: advisor
            image: {{ .Values.images.alcideAdvisorImage }}
            args:
              - --eula-sign
              - validate
              - cluster
              - --inCluster
              - --slack-api-token
              - $(ALCIDE_ADVISOR_EXPORT_SLACK_API_TOKEN)              
              - --slack-channel
              - "{{ .Values.slack.channel }}"
{{ if ne .Values.alcide.advisorProfileId ""}}
              - --profile-id
              - {{ .Values.alcide.advisorProfileId }}  
              - --organization
              - {{ .Values.alcide.orgId }}
              - --alcide-api-server
              - {{ .Values.alcide.apiServer }}               
              - --alcide-api-key
              - $(ALCIDE_API_KEY)                                         
{{ end }} 
{{ if ne .Values.s3.s3Url "" }}
              - --s3-export-url
              - {{ .Values.s3.s3Url }}                                         
{{ end }}              
              #- --debug
             
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              runAsUser: 10001
              readOnlyRootFilesystem: true
            env:
              - name: ALCIDE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: alcideApiKey           
              - name: ALCIDE_ADVISOR_EXPORT_SLACK_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: slackApiToken
              - name: ALCIDE_ADVISOR_EXPORT_AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: awsAccessKeyId
              - name: ALCIDE_ADVISOR_EXPORT_AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: awsSecretKey                                                  
            volumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs
          volumes:
            - name: ca-certificates
              emptyDir: {}
          restartPolicy: OnFailure
