---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: alcide-advisor
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronSchedule | quote }}
  # Keep the last run 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1  
  # Concurrency is not required
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        metadata:

          annotations: 
{{ toYaml .Values.jobTemplate.annotations | indent 12 }}
        spec:
          serviceAccountName: alcide-advisor
          containers:
          - name: advisor
            imagePullPolicy: Always
            image: {{ .Values.images.alcideAdvisorImage }}
            args:
              - --eula-sign
              - validate
              - cluster
              - --inCluster
              - --slack-api-token
              - $(ALCIDE_ADVISOR_EXPORT_SLACK_API_TOKEN)              
              - --slack-channel
              - "{{ .Values.slack.channel }}"
{{ if ne .Values.alcide.advisorProfileId ""}}
              - --profile-id
              - {{ .Values.alcide.advisorProfileId }}  
              - --organization
              - {{ .Values.alcide.orgId }}
              - --alcide-api-server
              - {{ .Values.alcide.apiServer }}               
              - --alcide-api-key
              - $(ALCIDE_API_KEY)                                         
{{ end }} 
{{ if ne .Values.s3.s3Url "" }}
              - --s3-export-url
              - {{ .Values.s3.s3Url }}                                         
{{ end }}     
{{ if ne .Values.prometheus.pushGateway "" }}
              - --prom-push-gateway
              - {{ .Values.prometheus.pushGateway }}                                         
{{ end }}          
              #- --debug
             
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsNonRoot: true
              runAsUser: 10001
              readOnlyRootFilesystem: true
            env:
              - name: ALCIDE_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: alcideApiKey           
              - name: ALCIDE_ADVISOR_EXPORT_SLACK_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: slackApiToken
              - name: ALCIDE_ADVISOR_EXPORT_AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: awsAccessKeyId
              - name: ALCIDE_ADVISOR_EXPORT_AWS_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: awsSecretKey 
              - name: ALCIDE_ADVISOR_EXPORT_PROM_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: promPushGatewayUsername 
              - name: ALCIDE_ADVISOR_EXPORT_PROM_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: alcide-advisor-exports
                    key: promPushGatewayPassword                                                                                          
          restartPolicy: OnFailure
