---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.clusterRole }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "proxy"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]